import Head from 'next/head'
import Link from 'next/link'
import groq from 'groq'
import client from '../client'






const Home = ({posts}) => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex justify-between items-center px-4 py-10 md:px-16'>
        <h2 className='text-4xl'>Stories</h2>
        <Link href="/stories">
          <a><button className='text-white bg-red-500 p-3 rounded hover:opacity-50 text-sm'>Alle Stories</button></a>
        </Link>
      </div>

      <div>
        <h1>Welcome to a blog!</h1>
      </div>
    </div>
  )
}



export default Home